// Ingredients-only seed data used by reset and seed scripts.
// Keep this file focused on data so scripts stay small and testable.

export type IngredientSeedObject = {
  name: string;
  categoryName: string;
  nutritionPer100g: {
    calories: number;
    proteins: number;
    fats: number;
    carbs: number;
  };
  units: Array<{
    unitName: string;
    gramsPerUnit: number;
  }>;
  icon: string | null;
  supermarketUrl: string | null;
};

export const ingredientSeedObjects: IngredientSeedObject[] = [
  // Produce
  { name: "Apple", categoryName: "Produce", nutritionPer100g: { calories: 52, proteins: 0.26, fats: 0.17, carbs: 13.81 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 180 }], icon: "apple.svg", supermarketUrl: "https://www.continente.pt/produto/maca-pink-lady-continente-7303767.html" },
  { name: "Avocado", categoryName: "Produce", nutritionPer100g: { calories: 160, proteins: 2.0, fats: 14.66, carbs: 8.53 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "avocado.svg", supermarketUrl: "https://www.continente.pt/produto/abacate-hass-continente-2076390.html" },
  { name: "Banana", categoryName: "Produce", nutritionPer100g: { calories: 89, proteins: 1.09, fats: 0.33, carbs: 22.84 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 120 }], icon: "banana.svg", supermarketUrl: "https://www.continente.pt/produto/banana-continente-2597619.html" },
  { name: "Basil (fresh)", categoryName: "Produce", nutritionPer100g: { calories: 23, proteins: 3.15, fats: 0.64, carbs: 2.65 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "leaves", gramsPerUnit: 0.5 }, { unitName: "handful", gramsPerUnit: 20 }], icon: "basil.svg", supermarketUrl: "https://www.continente.pt/produto/manjericao-fresco-continente-3842671.html" },
  { name: "Bean sprouts", categoryName: "Produce", nutritionPer100g: { calories: 30, proteins: 3.04, fats: 0.18, carbs: 5.94 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "beans.svg", supermarketUrl: "https://www.continente.pt/produto/rebentos-de-feijao-mungo-sem-gluten-continente-7367975.html" },
  { name: "Bell pepper", categoryName: "Produce", nutritionPer100g: { calories: 19.7, proteins: 0.72, fats: 0.11, carbs: 4.78 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 150 }], icon: "pepper.svg", supermarketUrl: "https://www.continente.pt/produto/pimento-vermelho-continente-2076826.html" },
  { name: "Blueberries", categoryName: "Produce", nutritionPer100g: { calories: 57.4, proteins: 0.7, fats: 0.31, carbs: 14.6 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "blueberries.svg", supermarketUrl: "https://www.continente.pt/produto/mirtilos-continente-8440878.html" },
  { name: "Broccoli", categoryName: "Produce", nutritionPer100g: { calories: 31, proteins: 2.57, fats: 0.34, carbs: 6.27 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 300 }], icon: "broccoli.svg", supermarketUrl: "https://www.continente.pt/produto/couve-brocolo-continente-2076764.html" },
  { name: "Butternut squash", categoryName: "Produce", nutritionPer100g: { calories: 41.7, proteins: 1.15, fats: 0.17, carbs: 10.5 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "pumpkin.svg", supermarketUrl: "https://www.continente.pt/produto/abobora-butternut-biologica-continente-bio-5593661.html" },
  { name: "Carrot", categoryName: "Produce", nutritionPer100g: { calories: 41, proteins: 0.93, fats: 0.24, carbs: 9.58 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 75 }], icon: "carrot.svg", supermarketUrl: "https://www.continente.pt/produto/cenoura-biologica-continente-bio-7382406.html" },
  { name: "Cauliflower", categoryName: "Produce", nutritionPer100g: { calories: 22.9, proteins: 1.64, fats: 0.24, carbs: 4.72 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "cauliflower.svg", supermarketUrl: "https://www.continente.pt/produto/couve-flor-continente-2076768.html" },
  { name: "Celery", categoryName: "Produce", nutritionPer100g: { calories: 14.8, proteins: 0.49, fats: 0.16, carbs: 3.32 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "stick", gramsPerUnit: 40 }], icon: "celery.svg", supermarketUrl: "https://www.continente.pt/produto/aipo-continente-5816322.html" },
  { name: "Cherry tomatoes", categoryName: "Produce", nutritionPer100g: { calories: 27, proteins: 0.83, fats: 0.63, carbs: 5.51 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 15 }], icon: "cherry-tomato.svg", supermarketUrl: "https://www.continente.pt/produto/tomate-cherry-com-rama-paloma-7371858.html" },
  { name: "Chili", categoryName: "Produce", nutritionPer100g: { calories: 40, proteins: 1.87, fats: 0.44, carbs: 8.81 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 10 }, { unitName: "pinch", gramsPerUnit: 0.36 }], icon: "chili.svg", supermarketUrl: "https://www.continente.pt/produto/piri-piri-continente-continente-6485691.html" },
  { name: "Chives", categoryName: "Produce", nutritionPer100g: { calories: 30, proteins: 3.27, fats: 0.73, carbs: 4.35 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 3 }], icon: "chive.svg", supermarketUrl: "https://www.continente.pt/produto/cebolinho-fresco-continente-3842593.html" },
  { name: "Coriander (fresh)", categoryName: "Produce", nutritionPer100g: { calories: 23, proteins: 2.13, fats: 0.52, carbs: 3.67 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "handful", gramsPerUnit: 15 }, { unitName: "leaves", gramsPerUnit: 0.2 }], icon: "coriander.svg", supermarketUrl: "https://www.continente.pt/produto/coentros-frescos-continente-continente-6690953.html" },
  { name: "Garlic", categoryName: "Produce", nutritionPer100g: { calories: 143, proteins: 6.62, fats: 0.38, carbs: 28.2 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "clove", gramsPerUnit: 3 }, { unitName: "tsp", gramsPerUnit: 2.8 }, { unitName: "piece", gramsPerUnit: 3 }], icon: "garlic.svg", supermarketUrl: "https://www.continente.pt/produto/alho-seco-continente-5104239.html" },
  { name: "Green onions", categoryName: "Produce", nutritionPer100g: { calories: 32, proteins: 1.83, fats: 0.19, carbs: 7.34 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "handful", gramsPerUnit: 15 }], icon: "spring-onion.svg", supermarketUrl: "https://www.continente.pt/produto/cebolinha-fresca-continente-7273061.html" },
  { name: "Iceberg lettuce", categoryName: "Produce", nutritionPer100g: { calories: 14.5, proteins: 0.74, fats: 0.07, carbs: 3.37 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "leaf", gramsPerUnit: 8 }], icon: "lettuce.svg", supermarketUrl: "https://www.continente.pt/produto/alface-iceberg-continente-8112513.html" },
  { name: "Leeks", categoryName: "Produce", nutritionPer100g: { calories: 61, proteins: 1.5, fats: 0.3, carbs: 14.15 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 130 }], icon: "leek.svg", supermarketUrl: "https://www.continente.pt/produto/alho-frances-cortado-continente-4419690.html" },
  { name: "Mango", categoryName: "Produce", nutritionPer100g: { calories: 70.6, proteins: 0.69, fats: 0.68, carbs: 17.4 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "mango.svg", supermarketUrl: "https://www.continente.pt/produto/manga-palmer-maturada-continente-4480831.html" },
  { name: "Mint", categoryName: "Produce", nutritionPer100g: { calories: 70, proteins: 3.75, fats: 0.94, carbs: 14.89 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "leaves", gramsPerUnit: 0.2 }], icon: "mint.svg", supermarketUrl: "https://www.continente.pt/produto/hortela-fresca-continente-6690954.html" },
  { name: "Mushrooms", categoryName: "Produce", nutritionPer100g: { calories: 22, proteins: 3.09, fats: 0.34, carbs: 3.26 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "cremini.svg", supermarketUrl: "https://www.continente.pt/produto/cogumelo-portobello-fresco-continente-6921727.html" },
  { name: "Portobello mushrooms", categoryName: "Produce", nutritionPer100g: { calories: 22, proteins: 2.11, fats: 0.35, carbs: 3.87 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "portobello.svg", supermarketUrl: "https://www.continente.pt/produto/cogumelo-portobello-fresco-continente-6921727.html" },
  { name: "Potato", categoryName: "Produce", nutritionPer100g: { calories: 77, proteins: 2.05, fats: 0.09, carbs: 17.49 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "potato.svg", supermarketUrl: "https://www.continente.pt/produto/batata-especial-assar-continente-3800355.html" },
  { name: "Pumpkin", categoryName: "Produce", nutritionPer100g: { calories: 26, proteins: 1.0, fats: 0.1, carbs: 6.5 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "pumpkin.svg", supermarketUrl: "https://www.continente.pt/produto/abobora-cubos-continente-6517122.html" },
  { name: "Raspberries", categoryName: "Produce", nutritionPer100g: { calories: 51.4, proteins: 1.01, fats: 0.19, carbs: 12.9 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "raspberry.svg", supermarketUrl: "https://www.continente.pt/produto/framboesa-continente-7622290.html" },
  { name: "Red cabbage", categoryName: "Produce", nutritionPer100g: { calories: 29.9, proteins: 1.24, fats: 0.21, carbs: 6.79 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 1000 }], icon: "red-cabbage.svg", supermarketUrl: "https://www.continente.pt/produto/metade-couve-roxa-continente-6219573.html" },
  { name: "Red onion", categoryName: "Produce", nutritionPer100g: { calories: 44, proteins: 0.94, fats: 0.1, carbs: 9.93 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 125 }, { unitName: "tbsp", gramsPerUnit: 10 }, { unitName: "ring", gramsPerUnit: 5 }], icon: "onion.svg", supermarketUrl: "https://www.continente.pt/produto/cebola-roxa-continente-5394157.html" },
  { name: "Strawberries", categoryName: "Produce", nutritionPer100g: { calories: 32.7, proteins: 0.64, fats: 0.22, carbs: 7.96 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "strawberry.svg", supermarketUrl: "https://www.continente.pt/produto/morango-premium-continente-5845080.html" },
  { name: "Sweet potato", categoryName: "Produce", nutritionPer100g: { calories: 77.4, proteins: 1.58, fats: 0.38, carbs: 17.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "sweet-potato.svg", supermarketUrl: "https://www.continente.pt/produto/batata-doce-continente-2076703.html" },
  { name: "Sweetcorn", categoryName: "Produce", nutritionPer100g: { calories: 72.9, proteins: 2.79, fats: 1.63, carbs: 14.7 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "corn.svg", supermarketUrl: "https://www.continente.pt/produto/milho-doce-sem-gluten-bonduelle-bonduelle-2384483.html" },
  { name: "White cabbage", categoryName: "Produce", nutritionPer100g: { calories: 27.9, proteins: 0.96, fats: 0.23, carbs: 6.38 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 1000 }], icon: "cabbage.svg", supermarketUrl: "https://www.continente.pt/produto/couve-branca-continente-2076762.html" },
  { name: "White onion", categoryName: "Produce", nutritionPer100g: { calories: 35, proteins: 0.89, fats: 0.13, carbs: 7.68 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 110 }, { unitName: "tbsp", gramsPerUnit: 10 }, { unitName: "ring", gramsPerUnit: 5 }], icon: "onion.svg", supermarketUrl: "https://www.continente.pt/produto/cebola-continente-4891584.html" },
  { name: "Hokkaido pumpkin", categoryName: "Produce", nutritionPer100g: { calories: 41.99, proteins: 1.25, fats: 0.18, carbs: 10.48 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "pumpkin.svg", supermarketUrl: "https://www.continente.pt/produto/abobora-hokaido-biologica-continente-bio-continente-bio-3865996.html" },

  // Dairy & Eggs
  { name: "Almond milk", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 19.3, proteins: 0.66, fats: 1.56, carbs: 0.67 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "ml", gramsPerUnit: 1.03 }], icon: "milk.svg", supermarketUrl: "https://www.continente.pt/produto/bebida-vegetal-amendoa-sem-acucar-continente-equilibrio-8244198.html" },
  { name: "Butter", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 717, proteins: 0.85, fats: 81.11, carbs: 0.06 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 4.7 }, { unitName: "tbsp", gramsPerUnit: 14.2 }, { unitName: "cup", gramsPerUnit: 227 }], icon: "butter.svg", supermarketUrl: "https://www.continente.pt/produto/manteiga-com-sal-milhafre-2228159.html" },
  { name: "Cheddar", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 408, proteins: 23.3, fats: 34.0, carbs: 2.44 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "cheddar.svg", supermarketUrl: "https://www.continente.pt/produto/queijo-emmental-ralado-president-4054579.html" },
  { name: "Cottage cheese (light)", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 84, proteins: 11.0, fats: 2.3, carbs: 4.31 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "cottage.svg", supermarketUrl: "https://www.continente.pt/produto/queijo-fresco-cottage-magro-danone-6869131.html" },
  { name: "Milk (semi-skimmed)", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 50, proteins: 3.36, fats: 1.9, carbs: 4.9 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "ml", gramsPerUnit: 1.03 }, { unitName: "l", gramsPerUnit: 1030 }, { unitName: "cup", gramsPerUnit: 240 }], icon: "milk.svg", supermarketUrl: "https://www.continente.pt/produto/leite-meio-gordo-pastagem-acores-milhafre-7055548.html" },
  { name: "Creme fraiche", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 393, proteins: 0.0, fats: 39.29, carbs: 3.57 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 15 }], icon: "sour cream.svg", supermarketUrl: "https://www.continente.pt/produto/natas-frescas-president-4403535.html" },
  { name: "Egg (L)", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 150, proteins: 12.3, fats: 10.3, carbs: 0.91 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 50 }], icon: "egg.svg", supermarketUrl: "https://www.continente.pt/produto/ovos-de-ar-livre-classe-m-l-continente-7411429.html" },
  { name: "Egg white", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 48, proteins: 10.1, fats: 0.16, carbs: 0.74 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 33 }], icon: "egg.svg", supermarketUrl: "https://www.continente.pt/produto/ovos-de-ar-livre-classe-m-l-continente-7411429.html" },
  { name: "Egg yolk", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 296, proteins: 15.6, fats: 25.1, carbs: 0.59 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 17 }], icon: "egg.svg", supermarketUrl: "https://www.continente.pt/produto/ovos-de-ar-livre-classe-m-l-matinados-6664918.html" },
  { name: "Greek yogurt (light)", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 73, proteins: 9.95, fats: 1.92, carbs: 3.94 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "cup", gramsPerUnit: 245 }, { unitName: "tbsp", gramsPerUnit: 15 }, { unitName: "tsp", gramsPerUnit: 5 }], icon: "yogurt.svg", supermarketUrl: "https://www.continente.pt/produto/iogurte-grego-mythos-ligeiro-natural-continente-equilibrio-7403702.html" },
  { name: "Mozzarella (light)", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 254, proteins: 24.3, fats: 15.9, carbs: 2.77 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "cheese.svg", supermarketUrl: "https://www.continente.pt/produto/queijo-mozzarella-light-galbani-2950765.html" },
  { name: "Parmesan", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 421, proteins: 29.6, fats: 28.0, carbs: 12.4 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 5 }], icon: "cheese.svg", supermarketUrl: "https://www.continente.pt/produto/queijo-parmigiano-reggiano-ralado-parmareggio-5013557.html" },
  { name: "Philadelphia (light)", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 264, proteins: 9.09, fats: 22.7, carbs: 5.59 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "cream-cheese.svg", supermarketUrl: "https://www.continente.pt/produto/queijo-para-barrar-light-philadelphia-7644941.html" },
  { name: "Plant milk", categoryName: "Dairy & Eggs", nutritionPer100g: { calories: 38.5, proteins: 3.55, fats: 2.12, carbs: 1.29 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "ml", gramsPerUnit: 1.02 }, { unitName: "l", gramsPerUnit: 1020 }, { unitName: "cup", gramsPerUnit: 240 }], icon: "soya-drink.svg", supermarketUrl: "https://www.continente.pt/produto/bebida-vegetal-aveia-e-amendoa-continente-equilibrio-7731978.html" },

  // Meat & Poultry
  { name: "Bacon", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 393, proteins: 13.7, fats: 37.1, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "bacon.svg", supermarketUrl: "https://www.continente.pt/produto/bacon-fumado-tiras-continente-continente-5243280.html" },
  { name: "Chicken breast", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 120, proteins: 22.5, fats: 2.62, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "chicken-breast.svg", supermarketUrl: "https://www.continente.pt/produto/strogonoff-de-frango-do-campo-campoaves-2964421.html" },
  { name: "Chicken burger patty", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 143, proteins: 17.44, fats: 8.1, carbs: 0.04 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 100 }], icon: "burger-meat.svg", supermarketUrl: "https://www.continente.pt/produto/hamburguer-de-frango-com-legumes-continente-equilibrio-7923641.html" },
  { name: "Chicken ham", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 98, proteins: 17.4, fats: 1.86, carbs: 2.92 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "chicken.svg", supermarketUrl: "https://www.continente.pt/produto/fiambre-de-peito-de-frango-fatiado-continente-7310431.html" },
  { name: "Chicken thighs (skinless, bone-in)", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 121, proteins: 19.66, fats: 4.12, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 160 }], icon: "chicken-leg.svg", supermarketUrl: "https://www.continente.pt/produto/coxas-de-frango-do-campo-continente-selecao-2839946.html" },
  { name: "Chicken thighs (skinless, boneless)", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 149.31, proteins: 18.61, fats: 7.92, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 140 }], icon: "chicken-leg.svg", supermarketUrl: "https://www.continente.pt/produto/coxas-de-frango-do-campo-continente-selecao-2839946.html" },
  { name: "Minced beef", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 176, proteins: 20.0, fats: 10.0, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "ground-beef.svg", supermarketUrl: "https://www.continente.pt/produto/preparado-de-carne-picada-de-bovino-continente-8442972.html" },
  { name: "Minced chicken", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 143, proteins: 17.44, fats: 8.1, carbs: 0.04 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "chicken.svg", supermarketUrl: "https://www.continente.pt/produto/preparado-de-carne-picada-de-frango-lusiaves-5476343.html" },
  { name: "Pancetta", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 500, proteins: 10.71, fats: 46.43, carbs: 3.57 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "bacon.svg", supermarketUrl: "https://www.continente.pt/produto/pancetta-cubos-levoni-7640138.html" },
  { name: "Pepperoni ham", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 504, proteins: 19.25, fats: 46.28, carbs: 1.18 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "salami.svg", supermarketUrl: "https://www.continente.pt/produto/pepperoni-fatias-corte-del-gusto-6914609.html" },
  { name: "Pork mince", categoryName: "Meat & Poultry", nutritionPer100g: { calories: 263, proteins: 16.88, fats: 21.19, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "pork.svg", supermarketUrl: "https://www.continente.pt/produto/preparado-de-carne-picada-de-porco-continente-8442975.html" },

  // Fish & Seafood
  { name: "Ray fish (with skin, bone-in)", categoryName: "Fish & Seafood", nutritionPer100g: { calories: 82, proteins: 17.81, fats: 0.67, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "stingray.svg", supermarketUrl: null },

  // Grains & Pasta
  { name: "Barley", categoryName: "Grains & Pasta", nutritionPer100g: { calories: 352, proteins: 9.91, fats: 1.16, carbs: 77.7 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "barley.svg", supermarketUrl: null },
  { name: "Buckwheat", categoryName: "Grains & Pasta", nutritionPer100g: { calories: 343, proteins: 13.25, fats: 3.4, carbs: 71.5 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "buckwheat.svg", supermarketUrl: "https://www.continente.pt/produto/trigo-sarraceno-seara-2962907.html" },
  { name: "Egg noodles", categoryName: "Grains & Pasta", nutritionPer100g: { calories: 384, proteins: 14.2, fats: 4.44, carbs: 71.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "nest", gramsPerUnit: 60 }], icon: "fettuccine.svg", supermarketUrl: "https://www.continente.pt/produto/massa-noodles-de-ovo-blue-dragon-8041413.html" },
  { name: "Millet", categoryName: "Grains & Pasta", nutritionPer100g: { calories: 378, proteins: 11.0, fats: 4.22, carbs: 72.8 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "millet.svg", supermarketUrl: null },
  { name: "Oats", categoryName: "Grains & Pasta", nutritionPer100g: { calories: 378.87, proteins: 13.5, fats: 5.89, carbs: 68.66 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "oatmeal.svg", supermarketUrl: "https://www.continente.pt/produto/flocos-aveia-finos-integral-pack-poupanca-continente-equilibrio-7246729.html" },
  { name: "Rice (white)", categoryName: "Grains & Pasta", nutritionPer100g: { calories: 370, proteins: 7.04, fats: 1.03, carbs: 80.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "cup", gramsPerUnit: 185 }], icon: "rice.svg", supermarketUrl: "https://www.continente.pt/produto/arroz-thai-jasmim-continente-4949517.html" },

  // Bread & Bakery
  { name: "Bread", categoryName: "Bread & Bakery", nutritionPer100g: { calories: 270, proteins: 9.43, fats: 3.59, carbs: 49.2 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "slice", gramsPerUnit: 35 }], icon: "bread.svg", supermarketUrl: "https://www.continente.pt/produto/pao-de-rio-maior-6913160.html" },
  { name: "Bread roll", categoryName: "Bread & Bakery", nutritionPer100g: { calories: 279, proteins: 9.0, fats: 3.2, carbs: 52.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 80 }], icon: "bread-loaf.svg", supermarketUrl: "https://www.continente.pt/produto/pao-de-rio-maior-6913160.html" },
  { name: "Dough ball (pizza)", categoryName: "Bread & Bakery", nutritionPer100g: { calories: 266, proteins: 8.9, fats: 3.2, carbs: 52.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "ball", gramsPerUnit: 150 }], icon: "bread.svg", supermarketUrl: null },

  // Legumes
  { name: "Chickpeas (cooked)", categoryName: "Legumes", nutritionPer100g: { calories: 164, proteins: 8.86, fats: 2.59, carbs: 27.4 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "chickpeas.svg", supermarketUrl: "https://www.continente.pt/produto/grao-de-bico-cozido-sem-gluten-compal-da-horta-2003596.html" },
  { name: "Kidney beans (cooked)", categoryName: "Legumes", nutritionPer100g: { calories: 127, proteins: 8.67, fats: 0.5, carbs: 22.8 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "kidney-beans.svg", supermarketUrl: "https://www.continente.pt/produto/feijao-encarnado-cozido-continente-2859501.html" },
  { name: "Red beans (canned)", categoryName: "Legumes", nutritionPer100g: { calories: 123, proteins: 7.8, fats: 1.26, carbs: 21.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "beans.svg", supermarketUrl: "https://www.continente.pt/produto/feijao-manteiga-cozido-continente-continente-2859772.html" },

  // Nuts & Seeds
  { name: "Almonds", categoryName: "Nuts & Seeds", nutritionPer100g: { calories: 584, proteins: 21.5, fats: 51.1, carbs: 20.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "almond.svg", supermarketUrl: "https://www.continente.pt/produto/miolo-de-amendoa-laminada-cimarrom-4963595.html" },
  { name: "Cashews", categoryName: "Nuts & Seeds", nutritionPer100g: { calories: 533, proteins: 17.4, fats: 38.9, carbs: 36.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "cashew.svg", supermarketUrl: "https://www.continente.pt/produto/caju-cru-continente-8114848.html" },
  { name: "Chia seeds", categoryName: "Nuts & Seeds", nutritionPer100g: { calories: 490, proteins: 17.0, fats: 32.9, carbs: 38.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "chia-seed.svg", supermarketUrl: "https://www.continente.pt/produto/sementes-de-chia-continente-8117186.html" },
  { name: "Nuts (mixed)", categoryName: "Nuts & Seeds", nutritionPer100g: { calories: 594, proteins: 17.3, fats: 51.4, carbs: 25.4 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "nuts.svg", supermarketUrl: "https://www.continente.pt/produto/mix-frutos-secos-lanches-essenciais-continente-8117228.html" },
  { name: "Peanut butter", categoryName: "Nuts & Seeds", nutritionPer100g: { calories: 589, proteins: 24.0, fats: 49.4, carbs: 22.7 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 16 }], icon: "peanuts.svg", supermarketUrl: "https://www.continente.pt/produto/manteiga-de-amendoim-com-pedacos-continente-equilibrio-8163576.html" },
  { name: "Peanuts", categoryName: "Nuts & Seeds", nutritionPer100g: { calories: 551, proteins: 23.2, fats: 43.3, carbs: 26.5 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "peanuts.svg", supermarketUrl: "https://www.continente.pt/produto/mix-frutos-secos-lanches-essenciais-continente-8117228.html" },

  // Oils & Condiments
  { name: "Apple vinegar", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 21, proteins: 0.0, fats: 0.0, carbs: 0.93 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "ml", gramsPerUnit: 1.01 }], icon: "vinegar.svg", supermarketUrl: "https://www.continente.pt/produto/vinagre-balsamico-macas-portuguesas-cristal-7866108.html" },
  { name: "Caesar sauce", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 542, proteins: 2.17, fats: 57.8, carbs: 3.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 15 }], icon: "sauce-jar.svg", supermarketUrl: "https://www.continente.pt/produto/molho-salada-caesar-top-down-heinz-4097418.html" },
  { name: "Chicken stock granules", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 267, proteins: 16.7, fats: 13.9, carbs: 18.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 4 }], icon: "spices-bottle.svg", supermarketUrl: "https://www.continente.pt/produto/caldo-de-galinha-cubos-continente-6896865.html" },
  { name: "Dijon mustard", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 61, proteins: 4.25, fats: 3.38, carbs: 5.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 5 }, { unitName: "tbsp", gramsPerUnit: 15 }], icon: "mustard.svg", supermarketUrl: "https://www.continente.pt/produto/mostarda-dijon-em-vidro-sem-gluten-continente-4376769.html" },
  { name: "Fish sauce", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 35, proteins: 5.06, fats: 0.01, carbs: 3.64 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 18 }], icon: "sauce-bottle.svg", supermarketUrl: null },
  { name: "Lemon juice", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 22, proteins: 0.35, fats: 0.24, carbs: 6.9 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 15 }, { unitName: "tsp", gramsPerUnit: 5 }, { unitName: "ml", gramsPerUnit: 1.03 }], icon: "lemon.svg", supermarketUrl: "https://www.continente.pt/produto/limao-continente-2076509.html" },
  { name: "Lime juice", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 25, proteins: 0.42, fats: 0.07, carbs: 8.42 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 5 }, { unitName: "tbsp", gramsPerUnit: 15 }, { unitName: "ml", gramsPerUnit: 1.03 }], icon: "lime.svg", supermarketUrl: "https://www.continente.pt/produto/lima-continente-2076510.html" },
  { name: "Maggi seasoning", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 53, proteins: 8.1, fats: 0.6, carbs: 4.9 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 15 }], icon: "spices-bottle.svg", supermarketUrl: "https://www.continente.pt/produto/molho-tempero-liquido-100--vegetal-maggi-maggi-7363645.html" },
  { name: "Malt vinegar", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 22, proteins: 0.0, fats: 0.0, carbs: 0.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "ml", gramsPerUnit: 1.01 }], icon: "vinegar.svg", supermarketUrl: null },
  { name: "Mayonnaise", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 263, proteins: 0.9, fats: 19.0, carbs: 23.9 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 14 }], icon: "mayonnaise.svg", supermarketUrl: "https://www.continente.pt/produto/maionese-light-sem-gluten-hellmanns-8460610.html" },
  { name: "Miso paste (white)", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 198, proteins: 12.8, fats: 6.01, carbs: 25.4 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 6 }], icon: "sauce-jar.svg", supermarketUrl: "https://www.amazon.es/-/en/Miso-White-Shiro-300g/dp/B01MYP7Y8A/ref=sr_1_3?crid=2ZX3JSAX3G8RB&dib=eyJ2IjoiMSJ9.e6JKiy92os-LcRS6D51myIyMuFQ867nFC7e_geGReOvXHkr030ywZzV5wFl181gHodkM_pGP8H8x91a3JRdrDelaZV5CY8fYnErChDF2oHwbDJpVHswfMQyMJ9Qn-kB0OOFE9YB1051VG1rWGXXO4ft0YEODK74lVuFPsln7eVXY6qVmyPW5yBeIFQ23tnsrUdmp_P2uFvKKjaG_mtewkWJOkUE5SENzEFygX6xsUq5AYAvVJeJJTdBCWu1qbfWyaTYz5Jgfxg6K1McScaTI6mbTINCYkC3QrGn1lHgR3M4.gLp5dvN0xNbkUyk4SKGyzIpTlz3h5EgfcViBIPfKQPY&dib_tag=se&keywords=white+miso+paste&qid=1764867158&sprefix=white+miso+paste%2Caps%2C90&sr=8-3" },
  { name: "Olive oil", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 884, proteins: 0.0, fats: 100.0, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 4.5 }, { unitName: "tbsp", gramsPerUnit: 13.5 }, { unitName: "ml", gramsPerUnit: 0.91 }], icon: "oil.svg", supermarketUrl: "https://www.continente.pt/produto/azeite-virgem-extra-spray-oliveira-da-serra-oliveira-da-serra-5311979.html?srsltid=AfmBOoro_l3CKMDSoKB0jmlAvjxkQj5ep5mUlGhMLQtnrlaK_4raagY2M4E" },
  { name: "Oyster sauce", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 51, proteins: 1.35, fats: 0.25, carbs: 10.9 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "cup", gramsPerUnit: 240 }], icon: "sauce-bottle.svg", supermarketUrl: null },
  { name: "Rapeseed oil", categoryName: "Oils & Condiments", nutritionPer100g: { calories: 884, proteins: 0.0, fats: 100.0, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 4.5 }, { unitName: "tbsp", gramsPerUnit: 13.5 }, { unitName: "ml", gramsPerUnit: 0.92 }], icon: "oil.svg", supermarketUrl: "https://www.continente.pt/produto/oleo-de-girassol-puro-fula-4403919.html" },

  // Spices & Herbs
  { name: "Almond extract", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 0.0, proteins: 0.0, fats: 0.0, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 4.2 }], icon: "vanilla-extract.svg", supermarketUrl: "https://www.continente.pt/pesquisa/?q=AROMA+AM%C3%8ANDOA" },
  { name: "Basil (dried)", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 233, proteins: 23.0, fats: 4.07, carbs: 47.8 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 1 }], icon: "basil.svg", supermarketUrl: "https://www.continente.pt/produto/manjericao-folha-em-frasco-margao-5585691.html" },
  { name: "Bay leaf", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 313, proteins: 7.61, fats: 8.36, carbs: 75.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "piece", gramsPerUnit: 0.2 }], icon: "bay-leaves.svg", supermarketUrl: "https://www.continente.pt/produto/louro-folha-em-saqueta-continente-6046671.html" },
  { name: "Black pepper", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 251, proteins: 10.4, fats: 3.26, carbs: 64.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 2.3 }, { unitName: "pinch", gramsPerUnit: 0.36 }], icon: "pepper-black.svg", supermarketUrl: "https://www.continente.pt/produto/mistura-de-pimentas-em-grao-em-saqueta-margao-7626343.html" },
  { name: "Cinnamon", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 247, proteins: 3.99, fats: 1.24, carbs: 80.6 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 2.6 }, { unitName: "tbsp", gramsPerUnit: 7.8 }], icon: "cinnamon.svg", supermarketUrl: "https://www.continente.pt/produto/canela-moida-em-saqueta-continente-6046675.html" },
  { name: "Coriander (dried)", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 298, proteins: 12.4, fats: 17.8, carbs: 55.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 5 }, { unitName: "tsp", gramsPerUnit: 1.7 }], icon: "coriander.svg", supermarketUrl: "https://www.continente.pt/produto/coentros-moidos-em-saqueta-margao-7636119.html" },
  { name: "Cumin (ground)", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 375, proteins: 17.8, fats: 22.3, carbs: 44.2 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 2.1 }], icon: "spices-bowl.svg", supermarketUrl: "https://www.continente.pt/produto/cominhos-moidos-em-saqueta-margao-2003335.html" },
  { name: "Curry leaves", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 64, proteins: 9.4, fats: 1.4, carbs: 8.28 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "leaves", gramsPerUnit: 0.2 }, { unitName: "handful", gramsPerUnit: 10 }], icon: "herbs-provence.svg", supermarketUrl: null },
  { name: "Curry powder", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 325, proteins: 14.3, fats: 14.0, carbs: 55.8 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 6 }], icon: "spices-bowl.svg", supermarketUrl: "https://www.continente.pt/produto/caril-em-frasco-margao-2003222.html" },
  { name: "Garlic powder", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 331, proteins: 16.6, fats: 0.73, carbs: 72.7 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 3.1 }], icon: "salt-garlic.svg", supermarketUrl: "https://www.continente.pt/produto/alho-picado-saqueta-margao-7576983.html" },
  { name: "Marjoram", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 271, proteins: 12.7, fats: 7.04, carbs: 60.6 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 2.0 }, { unitName: "tsp", gramsPerUnit: 0.7 }], icon: "herbs-provence.svg", supermarketUrl: null },
  { name: "Nutmeg", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 525, proteins: 5.84, fats: 36.3, carbs: 49.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 2.2 }], icon: "nutmeg.svg", supermarketUrl: "https://www.continente.pt/produto/noz-moscada-moida-em-frasco-margao-2826908.html" },
  { name: "Oregano (dried)", categoryName: "Spices & Herbs", nutritionPer100g: { calories: 265, proteins: 9.0, fats: 4.28, carbs: 68.9 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 1 }], icon: "oregano.svg", supermarketUrl: "https://www.continente.pt/produto/oregaos-folha-em-saqueta-continente-6057213.html" },

  // Canned & Jarred
  { name: "Chicken stock", categoryName: "Canned & Jarred", nutritionPer100g: { calories: 6, proteins: 0.64, fats: 0.21, carbs: 0.44 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "ml", gramsPerUnit: 1 }, { unitName: "l", gramsPerUnit: 1000 }], icon: "canned.svg", supermarketUrl: "https://www.continente.pt/produto/caldo-de-galinha-cubos-continente-6447115.html" },
  { name: "Cranberry sauce", categoryName: "Canned & Jarred", nutritionPer100g: { calories: 159, proteins: 0.9, fats: 0.15, carbs: 40.4 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 17 }], icon: "sauce-jar.svg", supermarketUrl: null },
  { name: "Passata", categoryName: "Canned & Jarred", nutritionPer100g: { calories: 29.1, proteins: 1.35, fats: 0.38, carbs: 6.33 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 15 }, { unitName: "tsp", gramsPerUnit: 5 }], icon: "pasta-sauce.svg", supermarketUrl: "https://www.continente.pt/produto/tomate-para-pizza-mutti-4049455.html" },
  { name: "Tomato puree", categoryName: "Canned & Jarred", nutritionPer100g: { calories: 34.8, proteins: 1.58, fats: 0.27, carbs: 8.04 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 16 }, { unitName: "tsp", gramsPerUnit: 5 }], icon: "pasta-sauce.svg", supermarketUrl: "https://www.continente.pt/produto/tomate-concentrado-compal-da-horta-5156834.html" },
  { name: "Tomatoes (tinned, chopped)", categoryName: "Canned & Jarred", nutritionPer100g: { calories: 18, proteins: 0.84, fats: 0.5, carbs: 3.32 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 15 }], icon: "tomato.svg", supermarketUrl: "https://www.continente.pt/produto/tomate-em-pedacos-continente-4310776.html" },

  // Baking
  { name: "Breadcrumbs", categoryName: "Baking", nutritionPer100g: { calories: 395, proteins: 13.4, fats: 5.3, carbs: 72.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 7 }], icon: "bread.svg", supermarketUrl: "https://www.continente.pt/produto/pao-ralado-3854224.html" },
  { name: "Cacao powder", categoryName: "Baking", nutritionPer100g: { calories: 228, proteins: 19.6, fats: 13.7, carbs: 57.9 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 5 }], icon: "cocoa.svg", supermarketUrl: "https://www.continente.pt/produto/cacau-magro-em-po-continente-equilibrio-2536010.html" },
  { name: "Cake flour", categoryName: "Baking", nutritionPer100g: { calories: 362, proteins: 8.2, fats: 0.86, carbs: 78.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "kg", gramsPerUnit: 1000 }, { unitName: "cup", gramsPerUnit: 120 }, { unitName: "tbsp", gramsPerUnit: 8 }, { unitName: "tsp", gramsPerUnit: 2.7 }], icon: "flour.svg", supermarketUrl: "https://www.continente.pt/produto/farinha-de-trigo-para-bolos-com-fermento-nacional-nacional-7683654.html" },
  { name: "Chocolate chips", categoryName: "Baking", nutritionPer100g: { calories: 480, proteins: 4.2, fats: 30.0, carbs: 63.9 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "chocolate.svg", supermarketUrl: "https://www.continente.pt/produto/granulado-de-chocolate-para-bolos-continente-2368271.html" },
  { name: "Custard powder", categoryName: "Baking", nutritionPer100g: { calories: 410, proteins: 6.9, fats: 6.4, carbs: 82.8 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "pack", gramsPerUnit: 40 }], icon: "spices-bowl.svg", supermarketUrl: null },
  { name: "Dry yeast", categoryName: "Baking", nutritionPer100g: { calories: 325, proteins: 40.4, fats: 7.61, carbs: 41.2 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "yeast.svg", supermarketUrl: "https://www.continente.pt/produto/fermento-de-padeiro-royal-7087665.html" },
  { name: "Plain flour", categoryName: "Baking", nutritionPer100g: { calories: 366, proteins: 10.9, fats: 1.48, carbs: 77.3 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "kg", gramsPerUnit: 1000 }, { unitName: "cup", gramsPerUnit: 120 }, { unitName: "tbsp", gramsPerUnit: 8 }, { unitName: "tsp", gramsPerUnit: 2.7 }], icon: "flour.svg", supermarketUrl: "https://www.continente.pt/produto/farinha-de-trigo-t55-continente-2388667.html" },
  { name: "Potato starch", categoryName: "Baking", nutritionPer100g: { calories: 357, proteins: 0.1, fats: 0.1, carbs: 83.1 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 2.7 }, { unitName: "tbsp", gramsPerUnit: 8.1 }], icon: "potato.svg", supermarketUrl: "https://www.continente.pt/produto/fecula-de-batata-cimarrom-6902535.html" },

  // Frozen
  { name: "Frozen peas", categoryName: "Frozen", nutritionPer100g: { calories: 53, proteins: 3.4, fats: 0.47, carbs: 11.2 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "peas.svg", supermarketUrl: "https://www.continente.pt/produto/ervilhas-continente-7917955.html" },
  { name: "Frozen seafood mix", categoryName: "Frozen", nutritionPer100g: { calories: 70, proteins: 12.0, fats: 1.0, carbs: 2.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "fish.svg", supermarketUrl: "https://www.continente.pt/produto/cocktail-de-marisco-congelado-continente-continente-7577623.html" },

  // Sweeteners
  { name: "Brown sugar", categoryName: "Sweeteners", nutritionPer100g: { calories: 380, proteins: 0.12, fats: 0.0, carbs: 98.1 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "cup", gramsPerUnit: 200 }, { unitName: "tsp", gramsPerUnit: 4.2 }], icon: "sugar.svg", supermarketUrl: "https://www.continente.pt/produto/acucar-mascavado-continente-7352655.html" },
  { name: "Erythritol", categoryName: "Sweeteners", nutritionPer100g: { calories: 0.0, proteins: 0.0, fats: 0.0, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "stevia.svg", supermarketUrl: "https://www.amazon.es/s?k=erythritol&crid=1VA3NUBZINY7O&sprefix=erythritol%2Caps%2C95&ref=nb_sb_noss_1" },
  { name: "Honey", categoryName: "Sweeteners", nutritionPer100g: { calories: 304, proteins: 0.3, fats: 0.0, carbs: 82.4 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tsp", gramsPerUnit: 7 }, { unitName: "tbsp", gramsPerUnit: 21 }], icon: "honey.svg", supermarketUrl: "https://www.continente.pt/produto/mel-flores-continente-4728172.html" },
  { name: "Pistachio cream", categoryName: "Sweeteners", nutritionPer100g: { calories: 561, proteins: 20.5, fats: 45.0, carbs: 27.7 }, units: [{ unitName: "g", gramsPerUnit: 1 }], icon: "pistachio.svg", supermarketUrl: "https://www.continente.pt/produto/pasta-de-pistacio-continente-equilibrio-8112033.html" },
  { name: "Sugar (powdered)", categoryName: "Sweeteners", nutritionPer100g: { calories: 389, proteins: 0.0, fats: 0.0, carbs: 99.8 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tbsp", gramsPerUnit: 8 }], icon: "sugar02.svg", supermarketUrl: "https://www.continente.pt/produto/acucar-em-po-sidul-sidul-6167995.html" },
  { name: "Sweetener tablets", categoryName: "Sweeteners", nutritionPer100g: { calories: 0.0, proteins: 0.0, fats: 0.0, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "tablet", gramsPerUnit: 0.1 }], icon: "stevia.svg", supermarketUrl: "https://www.continente.pt/produto/adocante-100-sticks-canderel-2917206.html" },

  // Other
  { name: "Dark rum", categoryName: "Other", nutritionPer100g: { calories: 231, proteins: 0.0, fats: 0.0, carbs: 0.0 }, units: [{ unitName: "g", gramsPerUnit: 1 }, { unitName: "cup", gramsPerUnit: 237 }, { unitName: "tbsp", gramsPerUnit: 14 }], icon: "rum-liquor.svg", supermarketUrl: "https://www.continente.pt/produto/havana-club-rum-anejo-especial-havana-club-8076046.html" },
];
